spring.application.name=MonitoringTool

server.port=4545

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========== MAIL CONFIG ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patilrushikesh1983@gmail.com
spring.mail.password=yfzyujtanazbpjxe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.from=patilrushikesh1983@gmail.com